### ISSUE TITLE
Indentation is broken in configmap.

### ISSUE THREAD

**Issue by alexluft** [mage-ai/helm-charts#33]
The indentation is broken in configmap.

values.yaml:
```yaml
config:
  FOO1: "F"
  FOO2: "O"
  FOO3: "O"
```

```shell
helm template mageai/mageai --values values.yaml --debug
[...]
Error: YAML parse error on mageai/templates/configmap.yaml: error converting YAML to JSON: yaml: line 12: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 12: did not find expected key
YAML parse error on mageai/templates/configmap.yaml
[...]
````

Results in:
```yaml
# Source: mageai/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: mageai-env
  labels:
    helm.sh/chart: mageai-0.1.5
    app.kubernetes.io/name: mageai
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.9.44"
    app.kubernetes.io/managed-by: Helm
data:
    FOO1: F
  FOO2: O
  FOO3: O
```

https://github.com/mage-ai/helm-charts/blob/207f044dd0b68e65127f4b1faba5a67f7f9bdf5d/charts/mageai/templates/configmap.yaml#L9

**Comment by sriniarul** [comment]
could u pls try with this, update the configmap template and try running.
{{ toYaml .Values.config | nindent 2 }}

**Comment by be99inner** [comment]
In my case, I tested with following template.
```yaml
{{ if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mageai.fullname" . }}-env
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
{{ end }}
```

For input like.

```yaml
config:
    REQUIRE_USER_AUTHENTICATION: "1"
    ENV: "dev"
```

It can render the perfect manifest.

```yaml
---
# Source: mageai/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-mageai-env
  labels:
    helm.sh/chart: mageai-0.1.0
    app.kubernetes.io/name: mageai
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.1.5"
    app.kubernetes.io/managed-by: Helm
data:
  ENV: dev
  REQUIRE_USER_AUTHENTICATION: "1"
```

II think it has the same issue on secret template.
