### ISSUE TITLE
Wrong Ingress Service Port

### ISSUE THREAD

**Issue by christopherscholz** [mage-ai/helm-charts#4]
The ingress is currently configured to forward to `$svcPort`, which is the container port. This is wrong. It should be forwarding to port `http`.

ingress.yaml
``` yaml
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
```

But the service maps the container port `$svcPort` to http port.

service.yaml
``` yaml
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
```

Threfore the ingress uses an unreachable port on the service.
Correct would be probably something like this:

ingress.yaml
``` yaml
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: http
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: http
              {{- end }}
```
