### ISSUE TITLE
Support dns configurations for scheduler and webserver

### ISSUE THREAD

**Issue by messerzen** [mage-ai/helm-charts#47]
I think it would be helpful to allow dns configurations on helm chart like `dnsConfig` and `dnsPolicy`. For now, I need to set some custom configurations for dns and I'm not able to do this directly in helm chart. To solve this problem, I'm generating the yaml files using `helm template` and deploying theses files. So, it would be helpful to set in helm chart, like this 

```
dnsPolicy: "ClusterFirstWithHostNet"
      dnsConfig:
        nameservers:
        - XXX.XXX.X.XXX
```
