### ISSUE TITLE
Duplicated pvc

### ISSUE THREAD

**Issue by younsl** [mage-ai/helm-charts#56]
## Problem

Due to the current helm template structure, the mageai-scheduler pod and the mageai-webserver pod are configured to refer to the same PVC.

```mermaid
---
title: mageai PVC architecture
---
flowchart LR
  w("mageai-webserver")
  s("mageai-scheduler")
  pvc("mageai-pvc")
  pv("mageai-pv")
  w --"/home/src"--> pvc
  s  --"/home/src"--> pvc
  pvc --> pv
```

```yaml
# pod spec for mageai-webserver and mageai-scheduler
spec:
  volumes:
  - name: mage-fs
    persistentVolumeClaim:
      claimName: mageai-pvc
```

Need to refactor chart template for persistentVolumeClaim resource and volume spec
